### ISSUE TITLE
Issue when long filename is passed to Temp::createFile()

### ISSUE THREAD

**Issue by jobrieniii** [keboola/php-temp#4] opened 2016-03-10 09:54 UTC
Ran into an issue when using `php-jsonparser` in cases where extreme path depth since filesystem couldn't write the file (in this case Mac OSX, 255 limit).

From my standpoint,  since this function  just creates Temp files that it could be handled by updating the createFile function to simply hash the filename passed to it to ensure uniqueness but not get fail if passed an extremely long filename.

My recommended fix was something like this:

```
    public function createFile($fileName, $preserve = false)
    {
        $this->initRunFolder();

        $fileInfo = new \SplFileInfo($this->getTmpPath() . '/' . sha1($fileName));

        $pathName = $fileInfo->getPathname();

        if (!file_exists(dirname($pathName))) {
            mkdir(dirname($pathName), 0777, true);
        }

        touch($pathName);
        $this->files[] = array(
            'filename' => $fileName,
            'file'  => $fileInfo,
            'preserve'  => $preserve
        );
        chmod($pathName, 0600);

        return $fileInfo;
    }

```

If you are open to the change, I can submit a pull request.

**Comment by jobrieniii** [comment] 2016-03-10 09:56
Actually looking a little more closely it may be worth catching in the Temp::createTmpFile.

**Comment by ondrejhlavacek** [comment] 2017-11-13 13:01
@jobrieniii Hi John,

thanks for the issue and very sorry for the delayed reaction. I'm trying to wrap my head around this issue. Do you have a bit of code, where it happens? I use the folder/file name sometimes for debugging purposes, so hashing it may not be the best option.

**Comment by odinuv** [comment] 2019-04-26 07:19
can't reproduce, closing

**Closed as completed by odinuv** 2019-04-26 07:19 UTC
