### ISSUE TITLE
Bug in removing non-empty temp directory

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/php-temp#3] opened 2016-03-02 13:56 UTC
`FileSystem::remove()` could remove non-empty directories unlike `rmdir()` function
(https://github.com/keboola/php-temp/commit/d76fc44d38c804565d8d13621ef9e1be27a49540#diff-b88a976e1fcdb795dd34382000376388L176)

**Comment by JakubMatejka** [comment] 2016-03-18 13:04
ping

**Comment by ondrejhlavacek** [comment] 2017-11-13 13:04
@JakubMatejka Is this still an issue? If so, can you please create a failing test with the intended behavior? Thanks!

**Comment by odinuv** [comment] 2019-04-26 07:19
can't reproduce, closing

**Closed as completed by odinuv** 2019-04-26 07:19 UTC
